# -*- coding: utf-8 -*-
"""CSE221_Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1pPoCewGCZ1bzG1_2CKUK0At1en8-tX

A. Two Sum Trouble
"""

n, s = input().split()
n = int(n)
s = int(s)
lt = input().split()
lt = [int(i) for i in lt]

left = 0
right = n - 1
found = False

while left < right:
    if lt[left] + lt[right] == s:
        print(left + 1, right + 1)
        found = True
        break
    elif lt[left] + lt[right] < s:
        left += 1
    else:
        right -= 1

if not found:
    print("-1")

"""B. A Beautiful Sorted List"""

n = int(input())
lt1 = input().split()
lt1 = [int(i) for i in lt1]

m = int(input())
lt2 = input().split()
lt2 = [int(i) for i in lt2]

lt3 = []
i, j = 0, 0

while i < n and j < m:
    if lt1[i] < lt2[j]:
        lt3.append(lt1[i])
        i += 1
    else:
        lt3.append(lt2[j])
        j += 1

while i < n:
    lt3.append(lt1[i])
    i += 1

while j < m:
    lt3.append(lt2[j])
    j += 1

for i in lt3:
    print(i, end=" ")

"""C. Longest Subarray Sum"""

n, k = input().split()
n = int(n)
k = int(k)
lt = input().split()
lt = [int(i) for i in lt]

left = 0
sum = 0
count = 0

for i in range (n):
    sum += lt[i]

    while sum > k and left <= i:
        sum -= lt[left]
        left += 1

    if sum <= k:
        count = max(count, i - left + 1)

print(count)

"""D. Can you Iterate the Binary String?"""

n = int(input())

for i in range (n):
    str = input()
    found = False
    count = 1

    for char in str:
        if char == "1":
            found = True
            print(count)
            break
        else:
            count += 1

    if not found:
        print("-1")

n = int(input())

for i in range (n):
    str = input()

    left = 0
    right = len(str) - 1
    c = -1

    while left <= right:
        mid = (left + right) // 2
        if str[mid] == "1":
            c = mid + 1
            right = mid - 1
        else:
            left = mid + 1

    print(c)

"""E. Count the Numbers"""

n, q = input().split()
n = int(n)
q = int(q)
a = input().split()
a = [int(i) for i in a]

for j in range (q):
    x, y = input().split()
    x, y = int(x), int(y)
    p = 0

    for k in range (n):
        if a[k] >= x and a[k] <= y:
            p += 1

    print(p)

n, q = input().split()
n = int(n)
q = int(q)
a = input().split()
a = [int(i) for i in a]

for j in range (q):
    x, y = input().split()
    x, y = int(x), int(y)

    left = 0
    right = n - 1
    p = 0

    while left <= right:
        mid = (left + right) // 2
        if a[mid] >= x:
            right = mid - 1
        else:
            left = mid + 1

    start = left

    left = 0
    right = n - 1

    while left <= right:
        mid = (left + right) // 2
        if a[mid] > y:
            right = mid - 1
        else:
            left = mid + 1

    end = left

    p = end - start
    print(p)
