# -*- coding: utf-8 -*-
"""CSE221_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWtPouVwHWpKm4-6E5ORq2NqV2uw7paJ

Task 1: Odd or Even?
"""

n = int(input())
for i in range (n):
    num = int(input())
    if num % 2 == 0:
        print(f"{num} is an Even number.")
    else:
        print(f"{num} is an Odd number.")

"""Task 2: Can you solve Arithmetic Expressions?"""

n = int(input())
for i in range (n):
    expression = input()
    function, a, c, b = expression.split(" ")
    a = float(a)
    b = float(b)
    if c == "+":
        print(a + b)
    elif c == "-":
        print(a - b)
    elif c == "*":
        print(a * b)
    elif c == "/":
        print(a / b)

"""Task 3: Array Reverse"""

n, k = input().split(" ")
n = int(n)
k = int(k)
arr = input().split()

for j in range (k):
    split = arr[:k]
    split.reverse()
for i in range (len(split)):
    print(split[i], end = " ")

n, k = input().split(" ")
n = int(n)
k = int(k)
arr = input().split()

for i in range (k-1,-1,-1):
    print(arr[i], end = " ")

"""Task 4: Fast Sum"""

t = int(input())
for i in range (t):
    n = int(input())
    sum = n * (n + 1) // 2
    print(sum)

"""Task 5: Bubble Sort"""

n = int(input())
arr = input().split()
for i in range (n):
    arr[i] = int(arr[i])

def bubbleSort(arr):
    for i in range (n):
        swapped = False
        for j in range (0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True
        if not swapped:
            break

bubbleSort(arr)
for _ in range (len(arr)):
    print(arr[_], end = " ")

n = int(input())
arr = list(map(int, input().split()))

def bubble_sort(arr):
    for i in range (len(arr)):
        swapped = False
        for j in range(0, len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True
        if not swapped:
            break

bubble_sort(arr)
for _ in range (len(arr)):
    print(arr[_], end = " ")

"""Task 6: Sorting Again??"""

# Selection Sort

n = int(input())
id = input().split()
marks = input().split()

for i in range (n):
    id[i] = int(id[i])
    marks[i] = int(marks[i])

count = 0

for i in range (n):
    maxIndex = i
    for j in range(i + 1, n):
        if (marks[j] > marks[maxIndex]) or (marks[j] == marks[maxIndex] and id[j] < id[maxIndex]):
            maxIndex = j

    if maxIndex != i:
        id[i], id[maxIndex] = id[maxIndex], id[i]
        marks[i], marks[maxIndex] = marks[maxIndex], marks[i]
        count += 1

print(f"Minimum swaps: {count}")
for i in range (n):
    print(f"ID: {id[i]} Mark: {marks[i]}")

"""Task 7: Trains?"""

n = int(input())
trains = []

for i in range (n):
    line = input()
    parts = line.split(" ")
    train = parts[0]
    destination = parts[-3]
    time = parts[-1]
    trains.append((train, destination, time))

for i in range (n-1):
    for j in range (n-i-1):
        hour1, min1 = (trains[j][2].split(":"))
        hour1, min1 = int(hour1), int(min1)
        hour2, min2 = (trains[j+1][2].split(":"))
        hour2, min2 = int(hour2), int(min2)
        if (trains[j][0] > trains[j+1][0]) or (trains[j][0]==trains[j+1][0] and (hour1<hour2 or (hour1==hour2 and min1<min2 ))):
            trains[j], trains[j+1] = trains[j+1], trains[j]

for train,destination,time in trains:
    print(f"{train} will departure for {destination} at {time}")